using Production.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Production.Models
{
    public class Detail
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [DisplayGridName("Название")]
        public string Name { get; set; }
        public override string ToString() => Name;
    }
}
