using Production.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Production.Models
{
    public class MakedDetail
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [DisplayGridName("Количество")]
        public int Count { get; set; }
        [DisplayGridName("Название детали")]
        public string DetailName { get; set; }
        [HideColumnIfAutoGenerated]
        public DateTime DateTime { get; set; } = DateTime.Today;
        [NotMapped]
        [DisplayGridName("Дата")]
        public string StrDateTime => DateTime.ToString("dd.MM.yyyy");
    }

    public class FailDetail
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [DisplayGridName("Количество")]
        public int Count { get; set; }
        [DisplayGridName("Название детали")]
        public string DetailName { get; set; }
        [HideColumnIfAutoGenerated]
        public DateTime DateTime { get; set; } = DateTime.Today;
        [NotMapped]
        [DisplayGridName("Дата")]
        public string StrDateTime => DateTime.ToString("dd.MM.yyyy");
    }
}
