using Production.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Production.Models
{
    /// <summary>
    /// Расписание
    /// </summary>
    public class Schedule
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [HideColumnIfAutoGenerated]
        public int TeamId { get; set; }
        [DisplayGridName("Бригада")]
        public Team Team { get; set; }
        [DisplayGridName("Смена")]
        public int Queue { get; set; }
        [DisplayGridName("Дата")]
        public DateTime Date { get; set; } = DateTime.Today;

        public override string ToString() => $"{Team.Name} #{Queue} / {Date.ToString("dd.MM.yyyy")}";
    }
}
