using Production.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Production.Models
{
    public class Schedule
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [HideColumnIfAutoGenerated]
        public int DetailId { get; set; }
        [DisplayGridName("Деталь")]
        public Detail Detail { get; set; }
        [HideColumnIfAutoGenerated]
        public DateTime DateTime { get; set; } = DateTime.Now;
        [DisplayGridName("Количество")]
        public int Count { get; set; }
        [DisplayGridName("Исполнено")]
        public bool Executed { get; set; } = false;
        [NotMapped]
        [DisplayGridName("Дата")]
        public string StrDateTime => DateTime.ToString("dd.MM.yyyy");
    }
}
