version: '3.4'

networks:
  translatepp:
    driver: bridge

services:
  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: AuthAPI/Dockerfile
    ports:
      - "8000:443"
    networks:
      - translatepp

  chatapi:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: ChatAPI/Dockerfile
    ports:
      - "8001:443"
    networks:
      - translatepp

  translatechatter:
    image: ${DOCKER_REGISTRY-}translatechatter
    build:
      context: .
      dockerfile: TranslateChatter/Dockerfile
    ports:
      - "8002:443"
    networks:
      - translatepp
  
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1437:1433"
    networks:
      - translatepp