version: '3.4'

services:
  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: AuthAPI/Dockerfile

  chatapi:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: ChatAPI/Dockerfile


  translatechatter:
    image: ${DOCKER_REGISTRY-}translatechatter
    build:
      context: .
      dockerfile: TranslateChatter/Dockerfile

