using Chemical.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Chemical.Models
{
    public class Detail
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [DisplayGridName("Название")]
        public string Name { get; set; }
        [HideColumnIfAutoGenerated]
        public List<DetailMaterial> DetailMaterials { get; set; }
        public override string ToString() => Name;
    }

    public class DetailMaterial
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [HideColumnIfAutoGenerated]
        public int DetailId { get; set; }
        [DisplayGridName("Деталь")]
        public Detail Detail { get; set; }
        [HideColumnIfAutoGenerated]
        public int RawMaterialId { get; set; }
        [DisplayGridName("Сырье")]
        public RawMaterial RawMaterial { get; set; }
    }
}
