using Chemical.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Chemical.Models
{
    [Serializable]
    public class Plan
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [HideColumnIfAutoGenerated]
        public int MaterialId { get; set; }
        [DisplayGridName("Сырье")]
        public RawMaterial Material { get; set; }
        [HideColumnIfAutoGenerated]
        public int StockId { get; set; }
        [DisplayGridName("Склад")]
        public Stock Stock { get; set; }
        [DisplayGridName("Начало производства")]
        public DateTime From { get; set; } = DateTime.Today;
        [DisplayGridName("Конец производства")]
        public DateTime To { get; set; } = DateTime.Today;
        [DisplayGridName("Количество")]
        public int Count { get; set; }
        [DisplayGridName("Исполнение")]
        public bool IsExercised { get; set; } = false;
        [DisplayGridName("Дата исполнения")]
        public DateTime? PlanExecute { get; set; }

        public override string ToString()
        {
            return $"{Material.Name}/{Stock.Name}/{Count}";
        }
    }
}
