using Chemical.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Documents;

namespace Chemical.Models
{
    /// <summary>
    /// Сырье
    /// </summary>
    [Serializable]
    public class RawMaterial
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [DisplayGridName("Название")]
        public string Name { get; set; }
        public override string ToString() => Name;
        [HideColumnIfAutoGenerated]
        public List<MaterialInStock> MaterialInStocks { get; set; }
    }
}
