using Chemical.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Documents;
using System.Windows.Media.Media3D;

namespace Chemical.Models
{
    [Serializable]
    public class Stock
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [DisplayGridName("Название")]
        public string Name { get; set; }

        public override string ToString() => Name;
    }

    [Serializable]
    public class MaterialInStock
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [HideColumnIfAutoGenerated]
        public int MaterialId { get; set; }
        [DisplayGridName("Cырье")]
        public RawMaterial Material { get; set; }
        [HideColumnIfAutoGenerated]
        public int StockId { get; set; }
        [DisplayGridName("Склад")]
        public Stock Stock { get; set; }
        [DisplayGridName("Количество")]
        public int Count { get; set; }
        [HideColumnIfAutoGenerated]
        public List<MaterialInStock> MaterialInStocks { get; set; }

        public override string ToString() => $"{Material.Name}/{Stock.Name}/{Count}";
    }
}
