using Garage.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace Garage.Models
{
    public enum ActionType
    {
        In,
        Out
    }

    public class Action
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [HideColumnIfAutoGenerated]
        public ActionType ActionType { get; set; }
        [HideColumnIfAutoGenerated]
        public int RentId { get; set; }
        [DisplayGridName("Аренда")]
        public virtual Rent Rent { get; set; }
        [HideColumnIfAutoGenerated]
        public DateTime DateTime { get; set; } = DateTime.Now;
        [DisplayGridName("Время и дата")]
        [NotMapped]
        public string DateTimeStr => DateTime.ToString("dd.MM.yyyy HH:MM");
        [NotMapped]
        [DisplayGridName("Тип")]
        public string ActionTypeStr => ActionType == ActionType.In ? "Въезд" : "Выезд";

        public override string ToString() => $"{ActionTypeStr} / {DateTimeStr} / {Rent}";
    }
}
