using Garage.Extensions.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace Garage.Models
{
    public class Rent
    {
        [HideColumnIfAutoGenerated]
        public int ID { get; set; }
        [HideColumnIfAutoGenerated]
        public int UserId { get; set; }
        [DisplayGridName("Пользователь")]
        public virtual User User { get; set; }
        [HideColumnIfAutoGenerated]
        public int BoxId { get; set; }
        [DisplayGridName("Бокс")]
        public virtual Box Box { get; set; }
        [HideColumnIfAutoGenerated]
        public DateTime StartDate { get; set; } = DateTime.Today;
        [HideColumnIfAutoGenerated]
        public DateTime? EndDate { get; set; }
        [NotMapped]
        [DisplayGridName("Дата начала")]
        public string StartDateStr => StartDate.ToString("dd.MM.yyyy HH:MM");
        [NotMapped]
        [DisplayGridName("Дата окончания")]
        public string EndDateStr => EndDate?.ToString("dd.MM.yyyy HH:MM");

        public override string ToString() => $"{User} / {Box} / {StartDate} / {EndDate}";
    }
}
